"""Add new pipeline columns

Revision ID: 8173f94ee140
Revises: 20251226_jwt_refresh
Create Date: 2025-12-30 07:30:47.249445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8173f94ee140'
down_revision: Union[str, None] = '20251226_jwt_refresh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('source_filters', sa.JSON(), nullable=True))
    op.add_column('pipelines', sa.Column('user_requirements', sa.JSON(), nullable=True))
    op.add_column('pipelines', sa.Column('estimated_cost', sa.JSON(), nullable=True))
    op.drop_index('idx_pipelines_deleted_at', table_name='pipelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pipelines_deleted_at', 'pipelines', ['deleted_at'], unique=False)
    op.drop_column('pipelines', 'estimated_cost')
    op.drop_column('pipelines', 'user_requirements')
    op.drop_column('pipelines', 'source_filters')
    # ### end Alembic commands ###
